### ISSUE TITLE
電磁弁をONにしたあと関節角をスライドバーから操作すると電磁弁がOFFになる

### ISSUE THREAD

**Issue by Tiryoh** [ryuichiueda/RobotDesign3#11]

**Comment by ryuichiueda** [comment]
むむ。なんででしょう・・・（JavaScript側で状態を更新していないかも・・・）

**Comment by Tiryoh** [comment]
https://github.com/ryuichiueda/RobotDesign3/blob/56b92526764d95903b9202cf784748f4988df1fe/cgi/angles.py#L46-L49

上記スクリプト内で"ON"以外はすべて"OFF"になるため、空文字が送信された際も"OFF"になっていることが原因のようです。修正します。

**Comment by Tiryoh** [comment]
#12 でプルリクエストを出した内容で2台以上のマニピュレータで動作確認ができたらマージします。
